version: '3.3'
services:
  basedatos:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: uthroot
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: uth123
  
  wordpress:
    depends_on:
      - basedatos
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: basedatos:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: uth123
volumes:
  db_data: {}